spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:backend-submodule/application-local.yml
      - application-default.yml

---

spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:backend-submodule/application-dev.yml
      - application-default.yml

---

spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:backend-submodule/application-prod.yml
      - application-default.yml