# 이 파일은 production level properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nainga?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 #나중에 원격 DB로 수정할 것
    username: #FILL YOUR DATABASE USERNAME
    password: #FILL YOUR DATABASE PASSWORD
  jpa:
    hibernate:
      ddl-auto: validate #validate로 하면 엔티티와 테이블이 정상적으로 매핑되어 있는지만 확인하고 DB에는 어떠한 변경 사항도 만들지 않는다.
    properties:
      hibernate:
        #          show_sql: true #밑에 org.hivernate.SQL과 겹치는데 얘는 System.out으로 찍는 거고 밑에는 로그로 찍는거. 얘를 안쓰는 걸 추천
        format_sql: true
        default_batch_fetch_size: 1000 # 배치 사이즈 글로벌 적용 (1+n) 문제 해결
  config:
    import:
      - env.yml

logging: #로그 레벨을 정하는 것
  level:
    org.hibernate.SQL: debug #JPA 하이버네이트가 생성하는 SQL이 다 보인다
    org.hibernate.type: trace
